### ISSUE TITLE
Why use lk.unlock(); in line 151?

### ISSUE THREAD

**Issue by CheYulin** [nbsdx/ThreadPool#10]
- Could not understand one line of code  
  -  std::unique_lockstd::mutex lk, the std::unique_lockstd::mutex is designed with RAII, why do you add extra  lk.unlock(); in line 151?
  - I am puzzled about that. Could you give me some hints? @nbsdx

**Comment by nbsdx** [comment]
It was a mistake. There's no reason for it to be there.
