### ISSUE TITLE
error: could not convert ‘__p.ThreadPool::next_job()::<lambda()>()’ from ‘void’ to ‘bool’

### ISSUE THREAD

**Issue by notdodo** [nbsdx/ThreadPool#4]
I'm getting this error `/usr/include/c++/5.3.0/condition_variable: In instantiation of ‘void std::condition_variable::wait(std::unique_lock<std::mutex>&, _Predicate) [with _Predicate = ThreadPool::next_job()::<lambda()>]’:
lib/../lib/ThreadPool.hpp:53:78:   required from here
/usr/include/c++/5.3.0/condition_variable:97:13: error: could not convert ‘__p.ThreadPool::next_job()::<lambda()>()’ from ‘void’ to ‘bool’
  while (!__p())` 

while using your header with lambda:

``` c++
ThreadPool<8> pool;
pool.AddJob( [it, &l, this]() {
    // Do something
    if (...) {
    }else {...}
    std::lock_guard<std::mutex> lock(this->mtx);
    {...}
});
```

**Comment by Fdhvdu** [comment]
@edoz90, because he forgets to add return in line 56

> job_available_var.wait( job_lock, [this]{ queue.size() || bailout; } );

should be

> job_available_var.wait( job_lock, [this]{return queue.size() || bailout; } );

BTW, my [threadpool](https://github.com/Fdhvdu/ThreadPool) is better than his.

**Comment by nbsdx** [comment]
@edoz90 Thanks, fixed. 

What compiler were you using? clang automatically picks up the return type & value AFAIK.
