### ISSUE TITLE
dynamic `ThreadCount`

### ISSUE THREAD

**Issue by notdodo** [nbsdx/ThreadPool#5]
Is there a way to make the number of threads (`ThreadCount`) dynamically used by the program?
Something like: `ThreadPool pool(std::thread::hardware_concurrency())`

**Comment by nbsdx** [comment]
No, the original use for this needed a static size at compile time, and I don't really want to split the code bases. I might add another file `ThreadPoolDynanic.h` with a dynamic version if I get around to it. But again, that would involve code duplication, which I'm against.

Translating it to be dynamically sized shouldn't be difficult, just remove the Size template argument, replace the `std::array` with a `std::vector`, and set the `vector` length in the constructor.
