### ISSUE TITLE
Compile on VS 2012/2013

### ISSUE THREAD

**Issue by DomGries** [nbsdx/ThreadPool#6]
`atomic_bool` does not have a constructor on VS 2012/2013 but can be replaced by `atomic<bool>` which has one. Same for `atomic_int`

http://stackoverflow.com/a/15751036

**Comment by nbsdx** [comment]
If VS isn't C++11 compliant, that's not my problem.

**Comment by fake-name** [comment]
Well, that's not helpful, and the change has no other effects.

Literally, just change:

```
    std::atomic_int         jobs_left;
    std::atomic_bool        bailout;
    std::atomic_bool        finished;
```

to

```
    std::atomic<int>        jobs_left;
    std::atomic<bool>       bailout;
    std::atomic<bool>       finished;
```

Additionally, this isn't MS flouting the standard, it's legitimately a bug in their STL that just hasn't been fixed yet.
